services:
    _defaults:
        autowire: true
        autoconfigure: true
    Sterzik\AdminerBundle\:
        resource: '../src/'
        exclude:
            - '../src/AdminerBundle.php'
    Sterzik\AdminerBundle\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

